<?php

/**
 * WCAG contrast checker for the MenoyeMan brand palette.
 *
 * Usage: php scripts/check-contrast.php
 * Prints a Markdown table of contrast ratios for every text/background pair
 * used by the design system. Output is copied into docs/BRAND.md.
 */

declare(strict_types=1);

/** Brand scale sampled/derived from the logo orange #F15A22 (see docs/BRAND.md). */
$scale = [
    'brand-50'  => '#FFF7ED',
    'brand-100' => '#FFEEDC',
    'brand-200' => '#FDD9B4',
    'brand-300' => '#F9B27B',
    'brand-400' => '#F58443',
    'brand-500' => '#F15A22', // logo orange (source of truth)
    'brand-600' => '#CC4210',
    'brand-700' => '#B2370E',
    'brand-800' => '#8E2D0F',
    'brand-900' => '#73270F',
];

$semantic = [
    'success-600' => '#15803D',
    'danger-600'  => '#B91C1C',
    'warning-500' => '#EAB308',
    'ink-900'     => '#1C1917', // warm dark (dark-mode base / body text)
    'ink-700'     => '#44403C',
    'ink-500'     => '#78716C',
    'white'       => '#FFFFFF',
];

$palette = $scale + $semantic;

function luminance(string $hex): float
{
    $hex = ltrim($hex, '#');
    $rgb = [
        hexdec(substr($hex, 0, 2)) / 255,
        hexdec(substr($hex, 2, 2)) / 255,
        hexdec(substr($hex, 4, 2)) / 255,
    ];
    $lin = array_map(
        fn (float $c): float => $c <= 0.04045 ? $c / 12.92 : pow(($c + 0.055) / 1.055, 2.4),
        $rgb
    );
    return 0.2126 * $lin[0] + 0.7152 * $lin[1] + 0.0722 * $lin[2];
}

function contrast(string $a, string $b): float
{
    $l1 = luminance($a);
    $l2 = luminance($b);
    [$hi, $lo] = $l1 >= $l2 ? [$l1, $l2] : [$l2, $l1];
    return ($hi + 0.05) / ($lo + 0.05);
}

/**
 * The pairs the design system actually uses.
 * "normal" needs AA 4.5:1, "large/UI" needs AA 3:1.
 */
$pairs = [
    // [fg, bg, usage, kind]
    ['white', 'brand-500', 'White text on logo orange buttons (large text only)', 'large'],
    ['white', 'brand-600', 'White text on 600 buttons/badges (default primary button)', 'normal'],
    ['white', 'brand-700', 'White text on 700 buttons (hover/pressed)', 'normal'],
    ['white', 'brand-800', 'White text on 800 (deep accents)', 'normal'],
    ['ink-900', 'brand-100', 'Body text on light brand surfaces', 'normal'],
    ['ink-900', 'brand-200', 'Body text on brand-200 chips', 'normal'],
    ['brand-700', 'white', 'Brand links/emphasis on white (light mode)', 'normal'],
    ['brand-800', 'white', 'Brand headings on white (light mode)', 'normal'],
    ['brand-600', 'white', 'Large brand text on white (>= 18.66px bold / 24px)', 'large'],
    ['brand-300', 'ink-900', 'Brand accent text on dark base (dark mode)', 'normal'],
    ['brand-400', 'ink-900', 'Brand buttons (dark text on 400) / accents (dark mode)', 'normal'],
    ['white', 'brand-800', 'White on brand-800 dark-mode buttons', 'normal'],
    ['white', 'ink-900', 'Primary text dark mode', 'normal'],
    ['brand-100', 'ink-900', 'Secondary text dark mode', 'normal'],
    ['ink-500', 'white', 'Muted text light mode', 'normal'],
    ['white', 'success-600', 'Success badges', 'normal'],
    ['white', 'danger-600', 'Error badges (never orange — destructive is red)', 'normal'],
    ['ink-900', 'warning-500', 'Warning badges (yellow, visually distinct from brand)', 'normal'],
];

echo "# Brand palette contrast report (WCAG 2.1)\n\n";
echo "Generated by `scripts/check-contrast.php` — ratio must be >= 4.5 for normal text (AA), >= 3 for large text/UI (AA).\n\n";
echo "| Foreground | Background | Usage | Kind | Ratio | AA |\n";
echo "|---|---|---|---|---|---|\n";

$fail = 0;
foreach ($pairs as [$fg, $bg, $usage, $kind]) {
    $ratio = contrast($palette[$fg], $palette[$bg]);
    $need = $kind === 'normal' ? 4.5 : 3.0;
    $ok = $ratio >= $need;
    if (! $ok) {
        $fail++;
    }
    printf(
        "| %s (%s) | %s (%s) | %s | %s | %.2f:1 | %s |\n",
        $fg,
        $palette[$fg],
        $bg,
        $palette[$bg],
        $usage,
        $kind,
        $ratio,
        $ok ? 'PASS' : '**FAIL**'
    );
}

echo "\n" . ($fail === 0 ? "All pairs pass.\n" : "{$fail} pair(s) FAIL.\n");
exit($fail === 0 ? 0 : 1);
